---
driver:
  name: ec2
  aws_ssh_key_id: kitchen
  region: us-west-2
  security_group_ids: ["sg-03b9ed660da7f5d26"]
  availability_zone: a
  require_chef_omnibus: true
  instance_type: t2.micro
  associate_public_ip: true
  shared_credentials_profile: kitchen

provisioner:
  name: chef_zero
  cookbook_path: cookbooks
  always_update_cookbooks: true
  retry_on_exit_code:
    - 35 # exit code signaling that the node is rebooting

platforms:
  #- name: Redhat7
  #  driver:
  #    image_id:  ami-223f945a
  #  transport:
  #    ssh_key: C:\Users\ks956797\.ec2\kitchen.pem
  #    username: ec2-user
  - name: ubuntu
    driver:
      image_id:  ami-4e79ed36
    transport:
      ssh_key: C:\Users\ks956797\.ec2\kitchen.pem
      username: ubuntu

suites:
  - name: default
    run_list:
      - recipe[nodejs-simple::default]

    attributes:
