---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu
    driver:
      box:  bento/ubuntu-14.04 
      network:
      - ["private_network", {ip: "192.168.33.34"}]
  #- name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[configuretomcat::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
